//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmFramework.DeployUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XrmFramework.DeployUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #region {0}
        ///		private List&lt;{1}&gt; {2} = new List&lt;{1}&gt;();
        ///		
        ///		public void Add{0}Responder({1} responder)
        ///		{{
        ///			{2}.Add(responder);
        ///		}}
        ///		
        ///		public {3}
        ///		{{
        ///			{4}
        ///			
        ///			if ({2}.Count &gt; 0)
        ///			{{
        ///				var responder = {2}.First();
        ///				{5}responder({6});
        ///				{2}.RemoveAt(0);
        ///				{7}
        ///			}}
        ///			else
        ///			{{
        ///				throw new NotImplementedException(&quot;Unexpected call to the method {0}&quot;);
        ///			}}
        ///		}}
        ///		#endregion.
        /// </summary>
        internal static string LoggedMethod {
            get {
                return ResourceManager.GetString("LoggedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using Model;
        ///using System;
        ///using System.Xml;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Microsoft.Xrm.Sdk.Query;
        ///using Microsoft.Crm.Sdk.Messages;
        ///using Microsoft.Xrm.Sdk;
        ///using Microsoft.Xrm.Sdk.Messages;
        ///
        ///namespace Plugins.Tests.Mocks.Services
        ///{{
        ///    public class {0} : {1}{2}
        ///    {{
        ///{3}
        ///    }}
        ///}}.
        /// </summary>
        internal static string MockFileShell {
            get {
                return ResourceManager.GetString("MockFileShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #region {0}
        ///		private List&lt;{1}&gt; {2} = new List&lt;{1}&gt;();
        ///		
        ///		public void Add{0}Responder({1} responder)
        ///		{{
        ///			{2}.Add(responder);
        ///		}}
        ///		
        ///		public {3}
        ///		{{
        ///			{4}
        ///			
        ///			if ({2}.Count &gt; 0)
        ///			{{
        ///				var responder = {2}.First();
        ///				{5}responder({6});
        ///				{2}.RemoveAt(0);
        ///				{7}
        ///			}}
        ///			else
        ///			{{
        ///				throw new NotImplementedException(&quot;Unexpected call to the method {0}&quot;);
        ///			}}
        ///		}}
        ///		#endregion
        ///.
        /// </summary>
        internal static string MockMethod {
            get {
                return ResourceManager.GetString("MockMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à             {0} = new {0}({1});.
        /// </summary>
        internal static string TestConstructorContent {
            get {
                return ResourceManager.GetString("TestConstructorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using Model;
        ///using System;
        ///using System.Xml;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Microsoft.Xrm.Sdk;
        ///using Microsoft.Xrm.Sdk.Query;
        ///using Microsoft.Crm.Sdk.Messages;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using Plugins.Tests.Mocks.Services;
        ///using Microsoft.Xrm.Sdk.Messages;
        ///
        ///namespace Plugins.Tests.Mocks
        ///{{
        ///    [TestClass]
        ///    public class {0}Tests : TestClass
        ///    {{
        ///        private {0} {0};
        ///
        ///        pro [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TestFileShell {
            get {
                return ResourceManager.GetString("TestFileShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à         [TestMethod]
        ///        public void {1}{2}Ok()
        ///        {{
        ///{3}
        ///            {0}.Add{1}Responder(new {7}(({8}) =&gt;
        ///                {{
        ///                    {6}
        ///            }}));
        ///
        ///            {0}.{1}{4}({5});
        ///        }}
        ///        #endregion
        ///
        ///.
        /// </summary>
        internal static string TestKoMethod {
            get {
                return ResourceManager.GetString("TestKoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à         #region {1}
        ///        [TestMethod]
        ///        public void {1}{2}Ko()
        ///        {{
        ///            var isException = false;
        ///{3}
        ///            try
        ///            {{
        ///                {0}.{1}{4}({5});
        ///            }}
        ///            catch (NotImplementedException e)
        ///            {{
        ///                Assert.IsTrue(e.Message.Contains(&quot;{1}&quot;));
        ///                isException = true;
        ///            }}
        ///            finally
        ///            {{
        ///                Assert.IsTrue(isException);
        ///            }}
        ///        }}
        ///
        ///.
        /// </summary>
        internal static string TestOkMethod {
            get {
                return ResourceManager.GetString("TestOkMethod", resourceCulture);
            }
        }
    }
}
