// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

#nullable enable

using System;
using System.Text;
using Model.Sdk;

namespace XrmFramework.Analyzers.Generators.Mapping;

/// <summary>
/// Writes the <c>ToBindingModel(Entity)</c> / <c>ToEntity(IOrganizationService?)</c> pair for a
/// <see cref="MappingModel"/>. Every property mapping is a visible, breakpoint-able line, so
/// debugging a mapping never means stepping through a reflection-based mapper.
///
/// Deliberately free of Roslyn symbols: it emits from the description alone, which is what lets
/// the same code serve a hand-written class and a class generated from a <c>.model</c> file.
/// </summary>
internal static class MappingEmitter
{
    /// <summary>Emits the full compilation unit — usings, namespace, partial class, both methods.</summary>
    public static string Generate(MappingModel model) => GenerateCode(model);

    /// <summary>Emits only the two methods, for a caller already inside the class body.</summary>
    public static void WriteMethods(CodeWriter sb, MappingModel model)
    {
        WriteToBindingModelMethod(sb, model);
        sb.Line();
        WriteToEntityMethod(sb, model);
    }

    private static string GenerateCode(MappingModel model)
    {
        var sb = new CodeWriter();

        sb.Line("// <auto-generated />");
        sb.Line();
        sb.Line("using System;");
        sb.Line("using System.CodeDom.Compiler;");
        sb.Line("using System.Collections.Generic;");
        sb.Line("using System.Diagnostics.CodeAnalysis;");
        sb.Line("using System.Linq;");
        sb.Line("using Microsoft.Xrm.Sdk;");
        sb.Line("using XrmFramework;");
        sb.Line("using XrmFramework.BindingModel;");
        sb.Line();

        if (model.Namespace is not null)
        {
            sb.Line($"namespace {model.Namespace}");
            sb.OpenBrace();
        }

        sb.Line("[GeneratedCode(\"XrmFramework.MappingGenerator\", \"1.0\")]");
        sb.Line("[ExcludeFromCodeCoverage]");
        sb.Line($"partial class {model.ClassName}");
        sb.OpenBrace();

        WriteToBindingModelMethod(sb, model);
        sb.Line();
        WriteToEntityMethod(sb, model);

        sb.CloseBrace(); // class

        if (model.Namespace is not null)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    // ── ToBindingModel ────────────────────────────────────────────────────────

    private static void WriteToBindingModelMethod(CodeWriter sb, MappingModel model)
    {
        sb.Line($"public static {model.ClassName} ToBindingModel(Entity entity)");
        sb.OpenBrace();

        sb.Line("if (entity == null)");
        sb.Indent(); sb.Line("return null;"); sb.Dedent();
        sb.Line();
        sb.Line($"if (entity.LogicalName != {model.EntityNameRef})");
        sb.Indent(); sb.Line("return null;"); sb.Dedent();
        sb.Line();
        sb.Line($"var model = new {model.ClassName}();");
        sb.Line("model.Id = entity.Id;");

        foreach (var ext in model.Extensions)
        {
            sb.Line();
            sb.Line($"// {ext.Name} — extension of the same entity");
            sb.Line($"model.{ext.Name} = {ext.TypeName}.ToBindingModel(entity);");
        }

        foreach (var prop in model.Properties)
        {
            sb.Line();
            WriteReadFromEntity(sb, prop);
        }

        sb.Line();
        sb.Line("return model;");
        sb.CloseBrace();
    }

    private static void WriteReadFromEntity(CodeWriter sb, MappingProperty prop)
    {
        var attrLabel = prop.IsList ? "MultiSelectPicklist" : prop.AttrType.ToString();
        sb.Line($"// {prop.Name} ({attrLabel})");

        if (prop.IsList)
        {
            WriteListRead(sb, prop);
            return;
        }

        sb.Line($"if (entity.Contains({prop.ColumnRef}))");
        sb.Indent();
        sb.Line($"model.{prop.Name} = {BuildReadExpr(prop)};");
        sb.Dedent();
    }

    private static void WriteListRead(CodeWriter sb, MappingProperty prop)
    {
        var elemType = prop.ListElemTypeName ?? "object";
        sb.Line($"if (entity.Contains({prop.ColumnRef}))");
        sb.OpenBrace();
        sb.Line($"foreach (var item in entity.GetOptionSetValues<{elemType}>({prop.ColumnRef}))");
        sb.Indent(); sb.Line($"model.{prop.Name}.Add(item);"); sb.Dedent();
        sb.CloseBrace();
    }

    private static string BuildReadExpr(MappingProperty prop) => prop.AttrType switch
    {
        AttributeTypeCode.Lookup   or
        AttributeTypeCode.Customer or
        AttributeTypeCode.Owner    => BuildLookupRead(prop),

        AttributeTypeCode.Money    => BuildMoneyRead(prop),

        AttributeTypeCode.Picklist or
        AttributeTypeCode.State    or
        AttributeTypeCode.Status   => BuildPicklistRead(prop),

        _ => $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})",
    };

    private static string BuildLookupRead(MappingProperty prop)
    {
        if (prop.InnerTypeName == "Guid")
        {
            var fallback = prop.IsNullable ? "" : " ?? Guid.Empty";
            return $"entity.GetAttributeValue<EntityReference>({prop.ColumnRef})?.Id{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    private static string BuildMoneyRead(MappingProperty prop)
    {
        if (prop.InnerTypeName is "decimal" || prop.TypeName is "decimal" or "decimal?")
        {
            var fallback = prop.IsNullable ? "" : " ?? default";
            return $"entity.GetAttributeValue<Money>({prop.ColumnRef})?.Value{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    private static string BuildPicklistRead(MappingProperty prop)
    {
        if (prop.IsEnum)
        {
            var enumType = prop.IsNullable ? prop.InnerTypeName : prop.TypeName;
            return $"entity.GetOptionSetValue<{enumType}>({prop.ColumnRef})";
        }

        if (prop.InnerTypeName is "int" || prop.TypeName is "int" or "int?")
        {
            var fallback = prop.IsNullable ? "" : " ?? default";
            return $"entity.GetAttributeValue<OptionSetValue>({prop.ColumnRef})?.Value{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    // ── ToEntity ──────────────────────────────────────────────────────────────

    private static void WriteToEntityMethod(CodeWriter sb, MappingModel model)
    {
        sb.Line("public Entity ToEntity(IOrganizationService service = null)");
        sb.OpenBrace();

        sb.Line($"var entity = new Entity({model.EntityNameRef}, Id);");

        foreach (var ext in model.Extensions)
        {
            sb.Line();
            sb.Line($"// {ext.Name} — extension of the same entity");
            sb.Line($"entity.MergeWith({ext.Name}?.ToEntity(service));");
        }

        foreach (var prop in model.Properties.Where(p => p.IsValidForUpdate))
        {
            sb.Line();
            WriteSetOnEntity(sb, prop, model.IsBindingModelBase);
        }

        sb.Line();
        sb.Line("return entity;");
        sb.CloseBrace();
    }

    private static void WriteSetOnEntity(CodeWriter sb, MappingProperty prop, bool isBindingModelBase)
    {
        var attrLabel = prop.IsList ? "MultiSelectPicklist" : prop.AttrType.ToString();
        sb.Line($"// {prop.Name} ({attrLabel})");

        if (isBindingModelBase)
        {
            sb.Line($"if (InitializedProperties.Contains(nameof({prop.Name})))");
            sb.OpenBrace();
        }

        WriteEntityAssignment(sb, prop);

        if (isBindingModelBase)
            sb.CloseBrace();
    }

    private static void WriteEntityAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.IsList)
        {
            sb.Line($"entity.SetOptionSetValues({prop.ColumnRef}, {prop.Name});");
            return;
        }

        switch (prop.AttrType)
        {
            case AttributeTypeCode.Lookup:
            case AttributeTypeCode.Customer:
            case AttributeTypeCode.Owner:
                WriteLookupAssignment(sb, prop);
                break;

            case AttributeTypeCode.Money:
                WriteMoneyAssignment(sb, prop);
                break;

            case AttributeTypeCode.Picklist:
            case AttributeTypeCode.State:
            case AttributeTypeCode.Status:
                WritePicklistAssignment(sb, prop);
                break;

            case AttributeTypeCode.DateTime:
                WriteDateTimeAssignment(sb, prop);
                break;

            default:
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
                break;
        }
    }

    private static void WriteLookupAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.InnerTypeName == "Guid")
        {
            var target = prop.LookupTargetRef ?? "\"unknown\"";
            if (prop.IsNullable)
            {
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name}.HasValue");
                sb.Indent();
                sb.Line($"? new EntityReference({target}, {prop.Name}.Value)");
                sb.Line(": null;");
                sb.Dedent();
            }
            else
            {
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name} != Guid.Empty");
                sb.Indent();
                sb.Line($"? new EntityReference({target}, {prop.Name})");
                sb.Line(": null;");
                sb.Dedent();
            }
        }
        else
        {
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        }
    }

    private static void WriteMoneyAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.InnerTypeName is "decimal" || prop.TypeName is "decimal" or "decimal?")
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new Money({prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = new Money({prop.Name});");
        }
        else
        {
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        }
    }

    private static void WritePicklistAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.IsEnum)
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new OptionSetValue((int){prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = {prop.Name} != default ? new OptionSetValue((int){prop.Name}) : null;");
        }
        else if (prop.InnerTypeName is "int" || prop.TypeName is "int" or "int?")
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new OptionSetValue({prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = new OptionSetValue({prop.Name});");
        }
        else
        {
            sb.Line($"entity.SetOptionSetValue({prop.ColumnRef}, {prop.Name});");
        }
    }

    private static void WriteDateTimeAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.IsNullable)
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        else
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name} != DateTime.MinValue ? {prop.Name} : (DateTime?)null;");
    }
}
