// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

#nullable enable

using System;
using System.Collections.Immutable;
using System.Text;
using Model.Sdk;

namespace XrmFramework.Analyzers.Generators.Mapping;

/// <summary>
/// Writes the <c>ToBindingModel(Entity)</c> / <c>ToEntity(IOrganizationService?)</c> pair for a
/// <see cref="MappingModel"/>. Every property mapping is a visible, breakpoint-able line, so
/// debugging a mapping never means stepping through a reflection-based mapper.
///
/// Deliberately free of Roslyn symbols: it emits from the description alone, which is what lets
/// the same code serve a hand-written class and a class generated from a <c>.model</c> file.
/// </summary>
internal static class MappingEmitter
{
    /// <summary>Emits the full compilation unit — usings, namespace, partial class, both methods.</summary>
    public static string Generate(MappingModel model) => GenerateCode(model);

    /// <summary>Emits only the two methods, for a caller already inside the class body.</summary>
    public static void WriteMethods(CodeWriter sb, MappingModel model)
    {
        WriteToBindingModelMethod(sb, model);
        sb.Line();
        WriteToEntityMethod(sb, model);
    }

    private static string GenerateCode(MappingModel model)
    {
        var sb = new CodeWriter();

        sb.Line("// <auto-generated />");
        sb.Line();
        sb.Line("using System;");
        sb.Line("using System.CodeDom.Compiler;");
        sb.Line("using System.Collections.Generic;");
        sb.Line("using System.Diagnostics.CodeAnalysis;");
        sb.Line("using System.Linq;");
        sb.Line("using Microsoft.Xrm.Sdk;");
        sb.Line("using XrmFramework;");
        sb.Line("using XrmFramework.BindingModel;");
        sb.Line();

        if (model.Namespace is not null)
        {
            sb.Line($"namespace {model.Namespace}");
            sb.OpenBrace();
        }

        sb.Line("[GeneratedCode(\"XrmFramework.MappingGenerator\", \"1.0\")]");
        sb.Line("[ExcludeFromCodeCoverage]");
        sb.Line($"partial class {model.ClassName}");
        sb.OpenBrace();

        WriteToBindingModelMethod(sb, model);
        sb.Line();
        WriteToEntityMethod(sb, model);

        sb.CloseBrace(); // class

        if (model.Namespace is not null)
            sb.CloseBrace(); // namespace

        return sb.ToString();
    }

    // ── ToBindingModel ────────────────────────────────────────────────────────

    private static void WriteToBindingModelMethod(CodeWriter sb, MappingModel model)
    {
        sb.Line($"public static {model.ClassName} ToBindingModel(Entity entity)");
        sb.OpenBrace();

        sb.Line("if (entity == null)");
        sb.Indent(); sb.Line("return null;"); sb.Dedent();
        sb.Line();
        sb.Line($"if (entity.LogicalName != {model.EntityNameRef})");
        sb.Indent(); sb.Line("return null;"); sb.Dedent();
        sb.Line();
        sb.Line($"var model = new {model.ClassName}();");
        sb.Line("model.Id = entity.Id;");

        foreach (var ext in model.Extensions)
        {
            sb.Line();
            sb.Line($"// {ext.Name} — extension of the same entity");
            sb.Line($"model.{ext.Name} = {ext.TypeName}.ToBindingModel(entity);");
        }

        foreach (var prop in model.Properties)
        {
            sb.Line();
            WriteReadFromEntity(sb, prop);
        }

        foreach (var rel in model.Relationships)
        {
            sb.Line();
            WriteRelationshipRead(sb, rel);
        }

        sb.Line();
        sb.Line("return model;");
        sb.CloseBrace();
    }

    /// <summary>
    /// Reads a one-to-many relationship's related entities by the relationship's schema name —
    /// mirroring the reflection mapper's own lookup, rather than <c>RelatedEntities</c>'
    /// dictionary equality, which a bare <see cref="Microsoft.Xrm.Sdk.Relationship"/> key cannot
    /// be trusted to match against one the platform filled in without a role.
    /// </summary>
    private static void WriteRelationshipRead(CodeWriter sb, MappingRelationship rel)
    {
        sb.Line($"// {rel.Name} — one-to-many relationship");
        sb.OpenBrace();
        sb.Line($"var relatedPair = entity.RelatedEntities.FirstOrDefault(r => r.Key.SchemaName == {rel.RelationshipRef});");
        sb.Line("if (relatedPair.Key != null)");
        sb.OpenBrace();
        sb.Line("foreach (var relatedEntity in relatedPair.Value?.Entities ?? Enumerable.Empty<Entity>())");
        sb.OpenBrace();
        sb.Line($"var relatedModel = {rel.ElementTypeName}.ToBindingModel(relatedEntity);");
        sb.Line("if (relatedModel != null)");
        sb.Indent(); sb.Line($"model.{rel.Name}.Add(relatedModel);"); sb.Dedent();
        sb.CloseBrace();
        sb.CloseBrace();
        sb.CloseBrace();
    }

    private static void WriteReadFromEntity(CodeWriter sb, MappingProperty prop)
    {
        var attrLabel = prop.IsList ? "MultiSelectPicklist" : prop.AttrType.ToString();
        sb.Line($"// {prop.Name} ({attrLabel})");

        if (prop.IsList)
        {
            WriteListRead(sb, prop);
            return;
        }

        sb.Line($"if (entity.Contains({prop.ColumnRef}))");
        sb.Indent();
        sb.Line($"model.{prop.Name} = {BuildReadExpr(prop)};");
        sb.Dedent();
    }

    private static void WriteListRead(CodeWriter sb, MappingProperty prop)
    {
        var elemType = prop.ListElemTypeName ?? "object";
        sb.Line($"if (entity.Contains({prop.ColumnRef}))");
        sb.OpenBrace();
        sb.Line($"foreach (var item in entity.GetOptionSetValues<{elemType}>({prop.ColumnRef}))");
        sb.Indent(); sb.Line($"model.{prop.Name}.Add(item);"); sb.Dedent();
        sb.CloseBrace();
    }

    private static string BuildReadExpr(MappingProperty prop)
    {
        // A projection lives under the alias the LinkEntity carries, not in the
        // entity's own column — which holds the EntityReference.
        if (prop.AliasedValueRef != null)
        {
            return $"entity.GetAliasedValue<{prop.TypeName}>({prop.AliasedValueRef})";
        }

        if (prop.IsEmbeddedLookupModel)
        {
            var relationshipRef = prop.EmbeddedRelationshipName != null
                ? $"\"{prop.EmbeddedRelationshipName}\""
                : "null";
            var isPolymorphic = prop.EmbeddedIsPolymorphic ? "true" : "false";

            return $"{prop.EmbeddedModelTypeName}.ToBindingModel("
                 + $"entity.GetEmbeddedLookupEntity({prop.ColumnRef}, {isPolymorphic}, {relationshipRef}))";
        }

        return prop.AttrType switch
    {
        AttributeTypeCode.Lookup   or
        AttributeTypeCode.Customer or
        AttributeTypeCode.Owner    => BuildLookupRead(prop),

        AttributeTypeCode.Money    => BuildMoneyRead(prop),

        AttributeTypeCode.Picklist or
        AttributeTypeCode.State    or
        AttributeTypeCode.Status   => BuildPicklistRead(prop),

            _ => $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})",
        };
    }

    private static string BuildLookupRead(MappingProperty prop)
    {
        if (prop.InnerTypeName == "Guid")
        {
            var fallback = prop.IsNullable ? "" : " ?? Guid.Empty";
            return $"entity.GetAttributeValue<EntityReference>({prop.ColumnRef})?.Id{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    private static string BuildMoneyRead(MappingProperty prop)
    {
        if (prop.InnerTypeName is "decimal" || prop.TypeName is "decimal" or "decimal?")
        {
            var fallback = prop.IsNullable ? "" : " ?? default";
            return $"entity.GetAttributeValue<Money>({prop.ColumnRef})?.Value{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    private static string BuildPicklistRead(MappingProperty prop)
    {
        if (prop.IsEnum)
        {
            var enumType = prop.IsNullable ? prop.InnerTypeName : prop.TypeName;
            return $"entity.GetOptionSetValue<{enumType}>({prop.ColumnRef})";
        }

        if (prop.InnerTypeName is "int" || prop.TypeName is "int" or "int?")
        {
            var fallback = prop.IsNullable ? "" : " ?? default";
            return $"entity.GetAttributeValue<OptionSetValue>({prop.ColumnRef})?.Value{fallback}";
        }

        return $"entity.GetAttributeValue<{prop.TypeName}>({prop.ColumnRef})";
    }

    // ── ToEntity ──────────────────────────────────────────────────────────────

    private static void WriteToEntityMethod(CodeWriter sb, MappingModel model)
    {
        sb.Line("public Entity ToEntity(IOrganizationService service = null)");
        sb.OpenBrace();

        sb.Line($"var entity = new Entity({model.EntityNameRef}, Id);");

        foreach (var ext in model.Extensions)
        {
            sb.Line();
            sb.Line($"// {ext.Name} — extension of the same entity");
            sb.Line($"entity.MergeWith({ext.Name}?.ToEntity(service));");
        }

        foreach (var prop in model.Properties.Where(p => p.IsValidForUpdate))
        {
            sb.Line();
            WriteSetOnEntity(sb, prop, model.IsBindingModelBase);
        }

        foreach (var rel in model.Relationships.Where(r => r.IsValidForUpdate))
        {
            sb.Line();
            WriteRelationshipWrite(sb, rel);
        }

        if (!model.AlternateKeys.IsEmpty)
        {
            sb.Line();
            WriteAlternateKeyResolution(sb, model.AlternateKeys);
        }

        sb.Line();
        sb.Line("return entity;");
        sb.CloseBrace();
    }

    /// <summary>
    /// Populates <c>entity.KeyAttributes</c> from the smallest alternate key whose columns all got
    /// a non-null value, when nothing set a real <c>Id</c> — an upsert-by-key request otherwise has
    /// nothing to key on. Mirrors the reflection mapper's <c>KeyInfos</c>: among the keys every
    /// column of which was actually written, the one with the fewest columns wins, first declared
    /// breaking a tie. Checked against the finished <c>Entity</c> rather than tracked as each
    /// attribute is written — equivalent, since a column's last write is the only one that survives
    /// into it, and simpler than threading a tracker through every property and extension.
    /// </summary>
    private static void WriteAlternateKeyResolution(CodeWriter sb, ImmutableArray<ImmutableArray<string>> alternateKeys)
    {
        sb.Line("// Alternate key — only when nothing set a real Id");
        sb.Line("if (entity.Id == Guid.Empty)");
        sb.OpenBrace();
        sb.Line("string[] smallestKey = null;");

        for (var i = 0; i < alternateKeys.Length; i++)
        {
            var columns = string.Join(", ", alternateKeys[i].Select(c => $"\"{c}\""));
            sb.Line($"var key{i} = new[] {{ {columns} }};");
            sb.Line($"if (key{i}.All(c => entity.Contains(c) && entity[c] != null) "
                  + $"&& (smallestKey == null || key{i}.Length < smallestKey.Length))");
            sb.Indent(); sb.Line($"smallestKey = key{i};"); sb.Dedent();
        }

        sb.Line("if (smallestKey != null)");
        sb.OpenBrace();
        sb.Line("foreach (var keyColumn in smallestKey)");
        sb.Indent(); sb.Line("entity.KeyAttributes[keyColumn] = entity[keyColumn];"); sb.Dedent();
        sb.CloseBrace();
        sb.CloseBrace();
    }

    /// <summary>
    /// Writes a one-to-many relationship's items as an <c>EntityCollection</c> under
    /// <c>entity.RelatedEntities</c>, mirroring the reflection mapper's <c>WriteRelationships</c>:
    /// unconditional whenever the property is non-null, empty list included.
    /// </summary>
    /// <remarks>
    /// <c>Relationship</c> and <c>EntityRole</c> are spelled out fully qualified: the generated
    /// file's <c>using XrmFramework;</c> brings in XrmFramework's own same-named
    /// <c>Relationship</c>/<c>EntityRole</c> (used by the generated <c>[Relationship]</c> attribute
    /// on <c>*Definition</c> classes) alongside the SDK's, and a bare reference to either would be
    /// ambiguous — exactly why the reflection mapper aliases them instead.
    /// </remarks>
    private static void WriteRelationshipWrite(CodeWriter sb, MappingRelationship rel)
    {
        sb.Line($"// {rel.Name} — one-to-many relationship");
        sb.Line($"if ({rel.Name} != null)");
        sb.OpenBrace();
        sb.Line("var relatedCollection = new EntityCollection();");
        sb.Line($"foreach (var item in {rel.Name})");
        sb.Indent(); sb.Line("relatedCollection.Entities.Add(item.ToEntity(service));"); sb.Dedent();
        sb.Line($"entity.RelatedEntities[new Microsoft.Xrm.Sdk.Relationship({rel.RelationshipRef}) "
              + "{ PrimaryEntityRole = Microsoft.Xrm.Sdk.EntityRole.Referenced }] = relatedCollection;");
        sb.CloseBrace();
    }

    private static void WriteSetOnEntity(CodeWriter sb, MappingProperty prop, bool isBindingModelBase)
    {
        var attrLabel = prop.IsList ? "MultiSelectPicklist" : prop.AttrType.ToString();
        sb.Line($"// {prop.Name} ({attrLabel})");

        if (isBindingModelBase)
        {
            sb.Line($"if (InitializedProperties.Contains(nameof({prop.Name})))");
            sb.OpenBrace();
        }

        WriteEntityAssignment(sb, prop);

        if (isBindingModelBase)
            sb.CloseBrace();
    }

    private static void WriteEntityAssignment(CodeWriter sb, MappingProperty prop)
    {
        // Read-only: the value belongs to the linked record, and the column it would be
        // written to holds the reference to that record.
        if (prop.AliasedValueRef != null)
        {
            return;
        }

        // Read-only for the same reason: the property carries the related model, not a value the
        // lookup column itself could hold. Writing the record back through its own model, on its
        // own table, is a separate call — not something this column's assignment can express.
        if (prop.IsEmbeddedLookupModel)
        {
            return;
        }

        if (prop.IsList)
        {
            sb.Line($"entity.SetOptionSetValues({prop.ColumnRef}, {prop.Name});");
            return;
        }

        switch (prop.AttrType)
        {
            case AttributeTypeCode.Lookup:
            case AttributeTypeCode.Customer:
            case AttributeTypeCode.Owner:
                WriteLookupAssignment(sb, prop);
                break;

            case AttributeTypeCode.Money:
                WriteMoneyAssignment(sb, prop);
                break;

            case AttributeTypeCode.Picklist:
            case AttributeTypeCode.State:
            case AttributeTypeCode.Status:
                WritePicklistAssignment(sb, prop);
                break;

            case AttributeTypeCode.DateTime:
                WriteDateTimeAssignment(sb, prop);
                break;

            default:
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
                break;
        }
    }

    private static void WriteLookupAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.InnerTypeName == "Guid")
        {
            var target = prop.LookupTargetRef ?? "\"unknown\"";
            if (prop.IsNullable)
            {
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name}.HasValue");
                sb.Indent();
                sb.Line($"? new EntityReference({target}, {prop.Name}.Value)");
                sb.Line(": null;");
                sb.Dedent();
            }
            else
            {
                sb.Line($"entity[{prop.ColumnRef}] = {prop.Name} != Guid.Empty");
                sb.Indent();
                sb.Line($"? new EntityReference({target}, {prop.Name})");
                sb.Line(": null;");
                sb.Dedent();
            }
        }
        else
        {
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        }
    }

    private static void WriteMoneyAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.InnerTypeName is "decimal" || prop.TypeName is "decimal" or "decimal?")
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new Money({prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = new Money({prop.Name});");
        }
        else
        {
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        }
    }

    private static void WritePicklistAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.IsEnum)
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new OptionSetValue((int){prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = {prop.Name} != default ? new OptionSetValue((int){prop.Name}) : null;");
        }
        else if (prop.InnerTypeName is "int" || prop.TypeName is "int" or "int?")
        {
            sb.Line(prop.IsNullable
                ? $"entity[{prop.ColumnRef}] = {prop.Name}.HasValue ? new OptionSetValue({prop.Name}.Value) : null;"
                : $"entity[{prop.ColumnRef}] = new OptionSetValue({prop.Name});");
        }
        else
        {
            sb.Line($"entity.SetOptionSetValue({prop.ColumnRef}, {prop.Name});");
        }
    }

    private static void WriteDateTimeAssignment(CodeWriter sb, MappingProperty prop)
    {
        if (prop.IsNullable)
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name};");
        else
            sb.Line($"entity[{prop.ColumnRef}] = {prop.Name} != DateTime.MinValue ? {prop.Name} : (DateTime?)null;");
    }
}
