<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>XrmFramework.Azure.Functions.Worker.Extensions</PackageId>
        <NuspecFile>$(MSBuildThisFileDirectory)XrmFramework.Azure.Functions.Worker.Extensions.nuspec</NuspecFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>


        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <NoWarn>$(NoWarn);1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Functions.Worker.Extensions.HttpApi" Version="3.0.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0"/>
        <PackageReference Include="MediatR" Version="12.4.1"/>
        <PackageReference Include="MediatR.Extensions.FluentValidation.AspNetCore" Version="5.1.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
        <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="OpenApi\" />
    </ItemGroup>

</Project>
