//HintName: ClientNamespace.Core.ISub2Service.logged.cs
// <auto-generated />
using ClientNamespace.Core;
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using XrmFramework;
#nullable disable

namespace ClientNamespace.Core
{
    [DebuggerStepThrough, CompilerGenerated]
    public class LoggedISub2Service : LoggedISubService, ISub2Service
    {
        protected new ISub2Service Service => (ISub2Service) base.Service;

        #region .ctor
        public LoggedISub2Service(IServiceContext context, ISub2Service service) : base(context, service)
        {
        }
        #endregion

        public void SubMethod2()
        {
            #region Parameters check
            #endregion

            var sw = new Stopwatch();
            sw.Start();

            Log(nameof(SubMethod2), "Start");

            Service.SubMethod2();

            Log(nameof(SubMethod2), "End : duration = {0}", sw.Elapsed);
        }
    }
}
