//HintName: ClientNamespace.Core.ISubService.logged.cs
// <auto-generated />
using ClientNamespace.Core;
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using XrmFramework;
#nullable disable

namespace ClientNamespace.Core
{
    [DebuggerStepThrough, CompilerGenerated]
    public class LoggedISubService : LoggedIService, ISubService
    {
        protected new ISubService Service => (ISubService) base.Service;

        #region .ctor
        public LoggedISubService(IServiceContext context, ISubService service) : base(context, service)
        {
        }
        #endregion

        public void SubMethod1()
        {
            #region Parameters check
            #endregion

            var sw = new Stopwatch();
            sw.Start();

            Log(nameof(SubMethod1), "Start");

            Service.SubMethod1();

            Log(nameof(SubMethod1), "End : duration = {0}", sw.Elapsed);
        }
    }
}
