//HintName: ContactModel.Mapping.g.cs
// <auto-generated />

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Microsoft.Xrm.Sdk;
using XrmFramework;
using XrmFramework.BindingModel;

[GeneratedCode("XrmFramework.MappingGenerator", "1.0")]
[ExcludeFromCodeCoverage]
partial class ContactModel
{
    public static ContactModel ToBindingModel(Entity entity)
    {
        if (entity == null)
            return null;

        if (entity.LogicalName != ContactDefinition.EntityName)
            return null;

        var model = new ContactModel();
        model.Id = entity.Id;

        // FullName (String)
        if (entity.Contains(ContactDefinition.Columns.FullName))
            model.FullName = entity.GetAttributeValue<string?>(ContactDefinition.Columns.FullName);

        // Email (String)
        if (entity.Contains(ContactDefinition.Columns.Email))
            model.Email = entity.GetAttributeValue<string?>(ContactDefinition.Columns.Email);

        // IsActive (Boolean)
        if (entity.Contains(ContactDefinition.Columns.IsActive))
            model.IsActive = entity.GetAttributeValue<bool?>(ContactDefinition.Columns.IsActive);

        // BirthDate (DateTime)
        if (entity.Contains(ContactDefinition.Columns.BirthDate))
            model.BirthDate = entity.GetAttributeValue<DateTime?>(ContactDefinition.Columns.BirthDate);

        // Revenue (Money)
        if (entity.Contains(ContactDefinition.Columns.Revenue))
            model.Revenue = entity.GetAttributeValue<Money>(ContactDefinition.Columns.Revenue)?.Value;

        // StatusCode (Picklist)
        if (entity.Contains(ContactDefinition.Columns.StatusCode))
            model.StatusCode = entity.GetOptionSetValue<ContactStatus>(ContactDefinition.Columns.StatusCode);

        // Interests (MultiSelectPicklist)
        if (entity.Contains(ContactDefinition.Columns.Interests))
        {
            foreach (var item in entity.GetOptionSetValues<ContactInterest>(ContactDefinition.Columns.Interests))
                model.Interests.Add(item);
        }

        // AccountId (Lookup)
        if (entity.Contains(ContactDefinition.Columns.AccountId))
            model.AccountId = entity.GetAttributeValue<EntityReference>(ContactDefinition.Columns.AccountId)?.Id ?? Guid.Empty;

        return model;
    }

    public Entity ToEntity(IOrganizationService service = null)
    {
        var entity = new Entity(ContactDefinition.EntityName, Id);

        // FullName (String)
        entity[ContactDefinition.Columns.FullName] = FullName;

        // Email (String)
        entity[ContactDefinition.Columns.Email] = Email;

        // IsActive (Boolean)
        entity[ContactDefinition.Columns.IsActive] = IsActive;

        // BirthDate (DateTime)
        entity[ContactDefinition.Columns.BirthDate] = BirthDate;

        // Revenue (Money)
        entity[ContactDefinition.Columns.Revenue] = Revenue.HasValue ? new Money(Revenue.Value) : null;

        // StatusCode (Picklist)
        entity[ContactDefinition.Columns.StatusCode] = StatusCode != default ? new OptionSetValue((int)StatusCode) : null;

        // Interests (MultiSelectPicklist)
        entity.SetOptionSetValues(ContactDefinition.Columns.Interests, Interests);

        // AccountId (Lookup)
        entity[ContactDefinition.Columns.AccountId] = AccountId != Guid.Empty
            ? new EntityReference(AccountDefinition.EntityName, AccountId)
            : null;

        return entity;
    }
}
