//HintName: ContactModelWithBase.Mapping.g.cs
// <auto-generated />

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Microsoft.Xrm.Sdk;
using XrmFramework;
using XrmFramework.BindingModel;

[GeneratedCode("XrmFramework.MappingGenerator", "1.0")]
[ExcludeFromCodeCoverage]
partial class ContactModelWithBase
{
    public static ContactModelWithBase ToBindingModel(Entity entity)
    {
        if (entity == null)
            return null;

        if (entity.LogicalName != ContactDefinition.EntityName)
            return null;

        var model = new ContactModelWithBase();
        model.Id = entity.Id;

        // FullName (String)
        if (entity.Contains(ContactDefinition.Columns.FullName))
            model.FullName = entity.GetAttributeValue<string?>(ContactDefinition.Columns.FullName);

        // Revenue (Money)
        if (entity.Contains(ContactDefinition.Columns.Revenue))
            model.Revenue = entity.GetAttributeValue<Money>(ContactDefinition.Columns.Revenue)?.Value;

        // StatusCode (Picklist)
        if (entity.Contains(ContactDefinition.Columns.StatusCode))
            model.StatusCode = entity.GetOptionSetValue<ContactStatus>(ContactDefinition.Columns.StatusCode);

        return model;
    }

    public Entity ToEntity(IOrganizationService service = null)
    {
        var entity = new Entity(ContactDefinition.EntityName, Id);

        // FullName (String)
        if (InitializedProperties.Contains(nameof(FullName)))
        {
            entity[ContactDefinition.Columns.FullName] = FullName;
        }

        // Revenue (Money)
        if (InitializedProperties.Contains(nameof(Revenue)))
        {
            entity[ContactDefinition.Columns.Revenue] = Revenue.HasValue ? new Money(Revenue.Value) : null;
        }

        // StatusCode (Picklist)
        if (InitializedProperties.Contains(nameof(StatusCode)))
        {
            entity[ContactDefinition.Columns.StatusCode] = StatusCode != default ? new OptionSetValue((int)StatusCode) : null;
        }

        return entity;
    }
}
