// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using CommandLine;

namespace XrmFramework.DeployUtils.CommandOptions;

public class TableSyncCommandOptions
{
    [Option("dll", Required = true,
        HelpText = "Path to the DLL to analyze (must contain *Definition classes with [EntityDefinition]).")]
    public string DllPath { get; set; } = string.Empty;

    [Option("tables-dir", Required = true,
        HelpText = "Directory containing the .table files to update or create.")]
    public string TablesDirectory { get; set; } = string.Empty;

    [Option("clean", Required = false, Default = false,
        HelpText = "Sets Select=false on columns absent from any Definition, and deletes .table files entirely generated by the tool with no CRM data.")]
    public bool Clean { get; set; }
}
