# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- v2.*

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:

- script: dotnet build XrmFramework.sln --configuration $(buildConfiguration) /p:PublicRelease=true
  displayName: Build
  workingDirectory: src
  
- task: CopyFiles@2
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'Packages'
    publishLocation: 'pipeline'