# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - master
    - v2.*
 paths:
  include:
    - src

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/XrmFramework.sln'
    arguments: '--configuration $(buildConfiguration) /p:PublicRelease=true'
    workingDirectory: 'src'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/XrmFramework.sln'
    workingDirectory: 'src'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/GeneratedNuGetPackages/$(buildConfiguration)/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'Packages'
    publishLocation: 'pipeline'