# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - master
      - v*
  paths:
    include:
      - src
variables:
  buildConfiguration: 'Release'
pool:
  vmImage: windows-latest

steps:
  - checkout: self
    fetchDepth: 0

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.0.0'

  - task: NuGetRestore@1
    inputs:
      solution: '**/XrmFramework.sln'
      selectOrConfig: 'select'

  - task: MSBuild@1
    inputs:
      solution: '**/XrmFramework.sln'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/p:PublicRelease=true'
      
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: '**/XrmFramework.sln'
      workingDirectory: 'src'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src/GeneratedNuGetPackages/$(buildConfiguration)/'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: 'Packages'
      publishLocation: 'pipeline'