# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - master
    - v2.*
 paths:
  include:
    - src

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- script: dotnet build XrmFramework.sln --configuration $(buildConfiguration) /p:PublicRelease=true
  displayName: Build
  workingDirectory: src
  
- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/GeneratedNuGetPackages/$(buildConfiguration)/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'Packages'
    publishLocation: 'pipeline'
