<Project Sdk="MSTest.Sdk/3.6.1">

    <PropertyGroup>
        <TargetFrameworks>net462;net8.0</TargetFrameworks>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <AssemblyOriginatorKeyFile>$(XrmFramework_KeyFile)</AssemblyOriginatorKeyFile>
        <SignAssembly>$(XrmFramework_EnableStrongNameSigning)</SignAssembly>
        <PublicSign>$(XrmFramework_PublicSign)</PublicSign>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XrmFramework\XrmFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

</Project>
