//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmFramework.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XrmFramework.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The callback must be public, not static and not abstract.
        /// </summary>
        public static string CheckCallbackVisibilityDescription {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Method &apos;{0}.{1}&apos; should be public, not static and not abstract.
        /// </summary>
        public static string CheckCallbackVisibilityMessageFormat {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback must be visible.
        /// </summary>
        public static string CheckCallbackVisibilityTitle {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin class must be public.
        /// </summary>
        public static string PluginVisibilityDescription {
            get {
                return ResourceManager.GetString("PluginVisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plugin class &apos;{0}&apos; should be public.
        /// </summary>
        public static string PluginVisibilityMessageFormat {
            get {
                return ResourceManager.GetString("PluginVisibilityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin class must be public.
        /// </summary>
        public static string PluginVisibilityTitle {
            get {
                return ResourceManager.GetString("PluginVisibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found.
        /// </summary>
        public static string Xrm0010_Description {
            get {
                return ResourceManager.GetString("Xrm0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or parent types.
        /// </summary>
        public static string Xrm0010_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback not found.
        /// </summary>
        public static string Xrm0010_Title {
            get {
                return ResourceManager.GetString("Xrm0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using call to ...Definition.EntityName.
        /// </summary>
        public static string Xrm0011_Description {
            get {
                return ResourceManager.GetString("Xrm0011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using call to ...Definition.EntityName.
        /// </summary>
        public static string Xrm0011_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer using call to ...Definition.EntityName.
        /// </summary>
        public static string Xrm0011_Title {
            get {
                return ResourceManager.GetString("Xrm0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference the method by using the nameof expression pattern.
        /// </summary>
        public static string Xrm0012_Description {
            get {
                return ResourceManager.GetString("Xrm0012_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;nameof&apos; expression to reference parameter &apos;{0}&apos; name.
        /// </summary>
        public static string Xrm0012_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;nameof&apos; expression.
        /// </summary>
        public static string Xrm0012_Title {
            get {
                return ResourceManager.GetString("Xrm0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced element should be a method declared in the containing class.
        /// </summary>
        public static string Xrm0013_Description {
            get {
                return ResourceManager.GetString("Xrm0013_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced element &apos;{0}&apos; should be a method declared in the containing class.
        /// </summary>
        public static string Xrm0013_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid callback method.
        /// </summary>
        public static string Xrm0013_Title {
            get {
                return ResourceManager.GetString("Xrm0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddStep should be called from AddSteps method.
        /// </summary>
        public static string Xrm0014_Description {
            get {
                return ResourceManager.GetString("Xrm0014_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddStep should be called from AddSteps method.
        /// </summary>
        public static string Xrm0014_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddStep should be called from AddSteps method.
        /// </summary>
        public static string Xrm0014_Title {
            get {
                return ResourceManager.GetString("Xrm0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingModel class should be partial.
        /// </summary>
        public static string Xrm0100_Description {
            get {
                return ResourceManager.GetString("Xrm0100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the class partial.
        /// </summary>
        public static string Xrm0100_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0100_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindingModel class should be partial.
        /// </summary>
        public static string Xrm0100_Title {
            get {
                return ResourceManager.GetString("Xrm0100_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is missing Converter methods, please add &quot;BindingModelSdkCodeGenerator&quot; as a custom tool for the file.
        /// </summary>
        public static string Xrm0101_Description {
            get {
                return ResourceManager.GetString("Xrm0101_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter methods not generated properly.
        /// </summary>
        public static string Xrm0101_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0101_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter methods not generated properly.
        /// </summary>
        public static string Xrm0101_Title {
            get {
                return ResourceManager.GetString("Xrm0101_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Definition class .EntityName in CrmEntityAttribute declaration.
        /// </summary>
        public static string Xrm0200_Description {
            get {
                return ResourceManager.GetString("Xrm0200_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Definition class .EntityName in CrmEntityAttribute declaration.
        /// </summary>
        public static string Xrm0200_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0200_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Definition class .EntityName in CrmEntityAttribute declaration.
        /// </summary>
        public static string Xrm0200_Title {
            get {
                return ResourceManager.GetString("Xrm0200_Title", resourceCulture);
            }
        }
    }
}
