<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--
      Tool for deploying plugins to Dataverse.
      net462 is required for compatibility with the Dynamics SDKs.
    -->
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference to this sample's Plugins project (to detect the plugins to deploy) -->
    <ProjectReference Include="$(RootFolder)/XrmFramework.Sample.Plugins/XrmFramework.Sample.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--
      Direct reference to the XrmFramework.DeployUtils project (instead of the NuGet package).
      Allows step-by-step debugging into the framework's deployment code.
    -->
    <ProjectReference Include="../../../src/XrmFramework.DeployUtils/XrmFramework.DeployUtils.csproj" />
  </ItemGroup>


  <Import Project="../../../src/XrmFramework.DeployUtils/build/net462/XrmFramework.DeployUtils.props" />


</Project>
