<Project Sdk="MSTest.Sdk/3.6.1">

   <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>

    <AssemblyOriginatorKeyFile>$(XrmFramework_KeyFile)</AssemblyOriginatorKeyFile>
    <SignAssembly>$(XrmFramework_EnableStrongNameSigning)</SignAssembly>
    <PublicSign>$(XrmFramework_PublicSign)</PublicSign>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XrmFramework.Core\XrmFramework.Core.csproj" />
  </ItemGroup>

</Project>
