//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmFramework.Analyzers {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XrmFramework.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The callback must be public, not static and not abstract..
        /// </summary>
        internal static string CheckCallbackVisibilityDescription {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Method &apos;{0}.{1}&apos; should be public, not static and not abstract.
        /// </summary>
        internal static string CheckCallbackVisibilityMessageFormat {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Callback must be visible.
        /// </summary>
        internal static string CheckCallbackVisibilityTitle {
            get {
                return ResourceManager.GetString("CheckCallbackVisibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A plugin class must be public..
        /// </summary>
        internal static string PluginVisibilityDescription {
            get {
                return ResourceManager.GetString("PluginVisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Plugin class &apos;{0}&apos; should be public.
        /// </summary>
        internal static string PluginVisibilityMessageFormat {
            get {
                return ResourceManager.GetString("PluginVisibilityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A plugin class must be public.
        /// </summary>
        internal static string PluginVisibilityTitle {
            get {
                return ResourceManager.GetString("PluginVisibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method not found..
        /// </summary>
        internal static string Xrm0010_Description {
            get {
                return ResourceManager.GetString("Xrm0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or parent types.
        /// </summary>
        internal static string Xrm0010_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Callback not found.
        /// </summary>
        internal static string Xrm0010_Title {
            get {
                return ResourceManager.GetString("Xrm0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefer using call to ...Definition.EntityName..
        /// </summary>
        internal static string Xrm0011_Description {
            get {
                return ResourceManager.GetString("Xrm0011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefer using call to ...Definition.EntityName.
        /// </summary>
        internal static string Xrm0011_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefer using call to ...Definition.EntityName.
        /// </summary>
        internal static string Xrm0011_Title {
            get {
                return ResourceManager.GetString("Xrm0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reference the method by using the nameof expression pattern..
        /// </summary>
        internal static string Xrm0012_Description {
            get {
                return ResourceManager.GetString("Xrm0012_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use &apos;nameof&apos; expression to reference parameter &apos;{0}&apos; name.
        /// </summary>
        internal static string Xrm0012_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use &apos;nameof&apos; expression.
        /// </summary>
        internal static string Xrm0012_Title {
            get {
                return ResourceManager.GetString("Xrm0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The referenced element should be a method declared in the containing class..
        /// </summary>
        internal static string Xrm0013_Description {
            get {
                return ResourceManager.GetString("Xrm0013_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The referenced element &apos;{0}&apos; should be a method declared in the containing class.
        /// </summary>
        internal static string Xrm0013_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid callback method.
        /// </summary>
        internal static string Xrm0013_Title {
            get {
                return ResourceManager.GetString("Xrm0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AddStep should be called from AddSteps method..
        /// </summary>
        internal static string Xrm0014_Description {
            get {
                return ResourceManager.GetString("Xrm0014_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AddStep should be called from AddSteps method.
        /// </summary>
        internal static string Xrm0014_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AddStep should be called from AddSteps method.
        /// </summary>
        internal static string Xrm0014_Title {
            get {
                return ResourceManager.GetString("Xrm0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BindingModel class should be partial..
        /// </summary>
        internal static string Xrm0100_Description {
            get {
                return ResourceManager.GetString("Xrm0100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make the class partial.
        /// </summary>
        internal static string Xrm0100_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0100_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BindingModel class should be partial.
        /// </summary>
        internal static string Xrm0100_Title {
            get {
                return ResourceManager.GetString("Xrm0100_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The object is missing Converter methods, please add &quot;BindingModelSdkCodeGenerator&quot; as a custom tool for the file..
        /// </summary>
        internal static string Xrm0101_Description {
            get {
                return ResourceManager.GetString("Xrm0101_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Converter methods not generated properly.
        /// </summary>
        internal static string Xrm0101_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0101_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Converter methods not generated properly.
        /// </summary>
        internal static string Xrm0101_Title {
            get {
                return ResourceManager.GetString("Xrm0101_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Definition class .EntityName in CrmEntityAttribute declaration..
        /// </summary>
        internal static string Xrm0200_Description {
            get {
                return ResourceManager.GetString("Xrm0200_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Definition class .EntityName in CrmEntityAttribute declaration.
        /// </summary>
        internal static string Xrm0200_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0200_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Definition class .EntityName in CrmEntityAttribute declaration.
        /// </summary>
        internal static string Xrm0200_Title {
            get {
                return ResourceManager.GetString("Xrm0200_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To be able to do unit tests on plugins, you need to use IDateTimeProvider interface instead of DateTime.Now or DateTime.UtcNow..
        /// </summary>
        internal static string Xrm0300_Description {
            get {
                return ResourceManager.GetString("Xrm0300_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To be able to do unit tests on plugins, you need to use IDateTimeProvider interface instead of DateTime.Now or DateTime.UtcNow.
        /// </summary>
        internal static string Xrm0300_MessageFormat {
            get {
                return ResourceManager.GetString("Xrm0300_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not use DateTime.Now or DateTome.UtcNow.
        /// </summary>
        internal static string Xrm0300_Title {
            get {
                return ResourceManager.GetString("Xrm0300_Title", resourceCulture);
            }
        }
    }
}
