<Project>
  <PropertyGroup>
    <!-- Dossier racine de la solution exemple, utilisé par les projets Utils -->
    <RootFolder>$(MSBuildThisFileDirectory)</RootFolder>

    <LangVersion>latest</LangVersion>

    <!-- Nom du projet Core de la solution exemple, utilisé par le DefinitionManager -->
    <XrmFrameworkCoreProjectName>XrmFramework.Sample.Core</XrmFrameworkCoreProjectName>

    <!-- Les projets samples gèrent leurs propres versions de dépendances. -->
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
