<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(XrmFramework_Runtime_TFM)</TargetFrameworks>
    <AssemblyName>XrmFramework.LogicApp</AssemblyName>
    <AssemblyOriginatorKeyFile>$(XrmFramework_KeyFile)</AssemblyOriginatorKeyFile>
    <SignAssembly>$(XrmFramework_SignAssembly)</SignAssembly>
    <PackageId>XrmFramework.LogicApp</PackageId>

    <NuspecFile>$(MSBuildThisFileDirectory)XrmFramework.LogicApp.nuspec</NuspecFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>

    <NoWarn>$(NoWarn);1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
