<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(XrmFramework_Runtime_TFM)</TargetFrameworks>
    <AssemblyName>XrmFramework</AssemblyName>
    <AssemblyOriginatorKeyFile>$(XrmFramework_KeyFile)</AssemblyOriginatorKeyFile>
    <SignAssembly>$(XrmFramework_EnableStrongNameSigning)</SignAssembly>
    <PublicSign>$(XrmFramework_PublicSign)</PublicSign>
    <PackageId>XrmFramework</PackageId>


    <NuspecFile>$(MSBuildThisFileDirectory)XrmFramework.nuspec</NuspecFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>


    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <NoWarn>$(NoWarn);1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.ComponentModel.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client.Dynamics" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\XrmFramework.Analyzers\XrmFramework.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\XrmFramework.Analyzers.CodeFixes\XrmFramework.Analyzers.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="**\*.table" />
        <AdditionalFiles Include="**\*.table" Exclude="bin/**;obj/**" />
    </ItemGroup>
</Project>
