// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.IO;
using CommandLine;
using Spectre.Console;
using XrmFramework.DeployUtils.CommandOptions;
using XrmFramework.DeployUtils.TableSync;

namespace XrmFramework.DeployUtils
{
    /// <summary>
    /// Migration tool taking a project from XrmFramework 2.* to 3.1 or above.
    /// </summary>
    /// <remarks>
    /// <para>
    /// In 2.*, the DefinitionManager wrote two files per table: a <c>.table</c> and its
    /// <c>*Definition.cs</c>. From 3.1 on, the <c>.table</c> is the single source of truth —
    /// <c>TableSourceFileGenerator</c> emits the Definition class at compile time — so the
    /// checked-in <c>.cs</c> becomes a duplicate that breaks the build.
    /// </para>
    /// <para>
    /// This tool performs the whole hand-over in one pass:
    /// it reflects over the last assembly compiled under 2.* to recover which columns the code
    /// actually uses, brings the <c>.table</c> files in line, then cleans up the
    /// <c>*Definition.cs</c> files left over next to them.
    /// </para>
    /// <para>
    /// It is meant to be run <b>once</b>, during the version upgrade. Afterwards the .NET tool's
    /// <c>tables pull</c> and the source generator take over.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // In the Deploy project's Program.cs:
    /// TableSyncHelper.SyncTables(args);
    /// </code>
    ///
    /// Expected arguments:
    /// <code>
    ///   --dll        &lt;path.dll&gt;      (required)
    ///   --tables-dir &lt;directory&gt;    (required)
    ///   --clean                       (optional)
    /// </code>
    /// </example>
    public static class TableSyncHelper
    {
        /// <summary>
        /// Migrates the .table files and the *Definition.cs files according to the
        /// <c>[EntityDefinition]</c> classes found in the DLL specified by <paramref name="args"/>.
        /// </summary>
        /// <remarks>
        /// Legacy entry point kept for compatibility: it performs the
        /// CommandLineParser parsing then delegates to <see cref="Sync(string, string, bool)"/>.
        /// On failure, the process is terminated via <see cref="Environment.Exit(int)"/>.
        /// New callers (Spectre CLI) should prefer <see cref="Sync(string, string, bool)"/>.
        /// </remarks>
        /// <param name="args">Command-line arguments.</param>
        public static void SyncTables(params string[] args)
        {
            Parser.Default
                  .ParseArguments<TableSyncCommandOptions>(args)
                  .WithParsed(options =>
                  {
                      var exitCode = Sync(options.DllPath, options.TablesDirectory, options.Clean);
                      if (exitCode != 0)
                          Environment.Exit(exitCode);
                  })
                  .WithNotParsed(errors =>
                  {
                      foreach (var error in errors)
                          AnsiConsole.MarkupLine($"[red]Parameter error:[/] {error}");

                      Environment.Exit(1);
                  });
        }

        // ──────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Migrates a directory of definitions from XrmFramework 2.* to 3.1 or above: brings the
        /// <c>.table</c> files in line with the <c>[EntityDefinition]</c> classes found in the provided
        /// DLL, then cleans up the <c>*Definition.cs</c> files those classes came from.
        /// </summary>
        /// <param name="dllPath">
        /// Path to the DLL to analyze — the assembly last compiled under 2.*, whose Definition classes
        /// record which columns the project's code actually uses.
        /// </param>
        /// <param name="tablesDirectory">Directory containing the .table and *Definition.cs files.</param>
        /// <param name="clean">
        /// Sets <c>Select=false</c> on orphaned columns and deletes .table files
        /// entirely generated by the tool with no CRM data.
        /// </param>
        /// <returns>
        /// Exit code: <c>0</c> success, <c>2</c> file/directory not found,
        /// <c>3</c> unexpected error.
        /// </returns>
        public static int Sync(string dllPath, string tablesDirectory, bool clean)
        {
            // Messages this tool composes itself stay ASCII: they must survive any console, even
            // one whose font has no glyph for a nicer character. Data it merely relays (CRM labels,
            // paths) is another matter, and is what the UTF-8 output encoding set in the CLI covers.
            AnsiConsole.MarkupLine("[bold]XrmFramework - migration of definitions from 2.* to 3.1+[/]");
            AnsiConsole.MarkupLine($"  DLL       : [cyan]{dllPath}[/]");
            AnsiConsole.MarkupLine($"  Directory : [cyan]{tablesDirectory}[/]");
            AnsiConsole.MarkupLine($"  Clean mode: [cyan]{(clean ? "yes" : "no")}[/]");
            AnsiConsole.WriteLine();

            try
            {
                // 1. Analyze the DLL
                AnsiConsole.MarkupLine("Analyzing DLL...");
                var definitions = DefinitionAnalyzer.ExtractDefinitions(dllPath);

                if (definitions.Count == 0)
                {
                    // Nothing to migrate *from*. Almost always the wrong --dll, so stop before
                    // touching any file rather than rewriting sources on a mistaken invocation.
                    AnsiConsole.MarkupLine(
                        "[yellow]No [[EntityDefinition]] class found in the DLL: migration stopped, " +
                        "nothing was modified. Check --dll points at the assembly compiled under 2.*.[/]");
                    return 0;
                }

                // 2. Bring the .table files in line — they become the single source of truth
                var syncer = new TableFileSyncer(tablesDirectory);
                syncer.Sync(definitions, clean);

                // 3. Clean up the *Definition.cs files the source generator now replaces
                AnsiConsole.WriteLine();
                AnsiConsole.MarkupLine("[bold]Cleaning up the *Definition.cs files[/]");
                var skipped = new DefinitionFileMigrator(tablesDirectory).Migrate();

                AnsiConsole.WriteLine();

                if (skipped > 0)
                    AnsiConsole.MarkupLine(
                        $"[yellow]Migration complete, but {skipped} *Definition.cs file(s) were left untouched " +
                        "(see above): review them by hand.[/]");
                else
                    AnsiConsole.MarkupLine("[green]Migration complete.[/]");

                return 0;
            }
            catch (FileNotFoundException ex)
            {
                AnsiConsole.MarkupLine($"[red]File not found:[/] {ex.FileName}");
                return 2;
            }
            catch (DirectoryNotFoundException ex)
            {
                AnsiConsole.MarkupLine($"[red]Directory not found:[/] {ex.Message}");
                return 2;
            }
            catch (Exception ex)
            {
                AnsiConsole.WriteException(ex);
                return 3;
            }
        }
    }
}
