// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.IO;
using CommandLine;
using Spectre.Console;
using XrmFramework.DeployUtils.CommandOptions;
using XrmFramework.DeployUtils.TableSync;

namespace XrmFramework.DeployUtils
{
    /// <summary>
    /// Entry point for synchronizing .table files from an assembly.
    /// </summary>
    /// <example>
    /// <code>
    /// // In the Deploy project's Program.cs:
    /// TableSyncHelper.SyncTables(args);
    /// </code>
    ///
    /// Expected arguments:
    /// <code>
    ///   --dll        &lt;path.dll&gt;      (required)
    ///   --tables-dir &lt;directory&gt;    (required)
    ///   --clean                       (optional)
    /// </code>
    /// </example>
    public static class TableSyncHelper
    {
        /// <summary>
        /// Synchronizes the .table files according to the <c>[EntityDefinition]</c> classes
        /// found in the DLL specified by <paramref name="args"/>.
        /// </summary>
        /// <remarks>
        /// Legacy entry point kept for compatibility: it performs the
        /// CommandLineParser parsing then delegates to <see cref="Sync(string, string, bool)"/>.
        /// On failure, the process is terminated via <see cref="Environment.Exit(int)"/>.
        /// New callers (Spectre CLI) should prefer <see cref="Sync(string, string, bool)"/>.
        /// </remarks>
        /// <param name="args">Command-line arguments.</param>
        public static void SyncTables(params string[] args)
        {
            Parser.Default
                  .ParseArguments<TableSyncCommandOptions>(args)
                  .WithParsed(options =>
                  {
                      var exitCode = Sync(options.DllPath, options.TablesDirectory, options.Clean);
                      if (exitCode != 0)
                          Environment.Exit(exitCode);
                  })
                  .WithNotParsed(errors =>
                  {
                      foreach (var error in errors)
                          AnsiConsole.MarkupLine($"[red]Parameter error:[/] {error}");

                      Environment.Exit(1);
                  });
        }

        // ──────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Synchronizes the <c>.table</c> files in the specified directory from the
        /// <c>[EntityDefinition]</c> classes found in the provided DLL.
        /// </summary>
        /// <param name="dllPath">Path to the DLL to analyze.</param>
        /// <param name="tablesDirectory">Directory containing the .table files.</param>
        /// <param name="clean">
        /// Sets <c>Select=false</c> on orphaned columns and deletes .table files
        /// entirely generated by the tool with no CRM data.
        /// </param>
        /// <returns>
        /// Exit code: <c>0</c> success, <c>2</c> file/directory not found,
        /// <c>3</c> unexpected error.
        /// </returns>
        public static int Sync(string dllPath, string tablesDirectory, bool clean)
        {
            AnsiConsole.MarkupLine("[bold]XrmFramework · .table file synchronization[/]");
            AnsiConsole.MarkupLine($"  DLL       : [cyan]{dllPath}[/]");
            AnsiConsole.MarkupLine($"  Directory : [cyan]{tablesDirectory}[/]");
            AnsiConsole.MarkupLine($"  Clean mode: [cyan]{(clean ? "yes" : "no")}[/]");
            AnsiConsole.WriteLine();

            try
            {
                // 1. Analyze the DLL
                AnsiConsole.MarkupLine("Analyzing DLL...");
                var definitions = DefinitionAnalyzer.ExtractDefinitions(dllPath);

                if (definitions.Count == 0)
                {
                    AnsiConsole.MarkupLine("[yellow]No [EntityDefinition] class found in the DLL.[/]");
                    return 0;
                }

                // 2. Synchronize the .table files
                var syncer = new TableFileSyncer(tablesDirectory);
                syncer.Sync(definitions, clean);

                AnsiConsole.WriteLine();
                AnsiConsole.MarkupLine("[green]Synchronization complete.[/]");
                return 0;
            }
            catch (FileNotFoundException ex)
            {
                AnsiConsole.MarkupLine($"[red]File not found:[/] {ex.FileName}");
                return 2;
            }
            catch (DirectoryNotFoundException ex)
            {
                AnsiConsole.MarkupLine($"[red]Directory not found:[/] {ex.Message}");
                return 2;
            }
            catch (Exception ex)
            {
                AnsiConsole.WriteException(ex);
                return 3;
            }
        }
    }
}
