// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace XrmFramework.DeployUtils.TableSync
{
    /// <summary>
    /// Information extracted from a *Definition class ([EntityDefinition]) in an assembly.
    /// </summary>
    public sealed class DefinitionInfo
    {
        /// <summary>Table name (.table filename without extension), e.g. "Contact".</summary>
        public string TableName { get; set; } = string.Empty;

        /// <summary>Logical name of the CRM entity, e.g. "contact".</summary>
        public string EntityName { get; set; } = string.Empty;

        /// <summary>Collection name of the CRM entity, e.g. "contacts". Null if absent.</summary>
        public string EntityCollectionName { get; set; }

        /// <summary>Columns declared in the nested Columns class.</summary>
        public IReadOnlyList<DefinitionColumnInfo> Columns { get; set; } = new List<DefinitionColumnInfo>();

        /// <summary>
        /// True if the class is decorated with [GeneratedCode("XrmFramework", "2.0")] —
        /// i.e. entirely generated by the Roslyn TableSourceFileGenerator.
        /// </summary>
        public bool IsFullyGenerated { get; set; }
    }
}
