//HintName: MyPlugin_Create_contact_SessionTests.g.cs
// <auto-generated/>
// Généré par XrmFramework.RemoteDebugger.Generator
// Ne pas modifier ce fichier manuellement.
// Pour régénérer, relancez simplement la compilation après modification des fichiers .pluginsession.json.

using System.Threading.Tasks;
using VerifyXunit;
using Xunit;
using XrmFramework.RemoteDebugger.Common;

namespace XrmFramework.RemoteDebugger.Generated
{
    /// <summary>
    /// Tests unitaires générés automatiquement pour <c>MyPlugin_Create_contact</c>.
    /// Chaque méthode rejoue une session de débogage distant enregistrée
    /// et vérifie que le contexte de sortie correspond au snapshot Verify.
    /// </summary>
    [UsesVerify]
    public class MyPlugin_Create_contact_SessionTests
    {
        /// <summary>
        /// Rejoue la session enregistrée depuis le fichier : MyPlugin_Create_contact.pluginsession.json
        /// </summary>
        [Fact]
        public async Task Session_MyPlugin_Create_contact()
        {
            // JSON de la session enregistrée lors du débogage distant
            // (intégré directement pour éviter toute dépendance aux fichiers externes)
            const string sessionJson = @"{
  ""pluginTypeName"": ""MyPlugin"",
  ""message"": ""Create"",
  ""stage"": 20,
  ""entityName"": ""contact"",
  ""capturedAt"": ""2025-01-01T00:00:00Z"",
  ""inputParameters"": {},
  ""preImages"": {},
  ""postImages"": {}
}";

            // Exécuter le plugin avec le contexte d'entrée enregistré,
            // en rejouant tous les appels CRM depuis les réponses enregistrées.
            var outputContext = PluginTestRunner.RunFromJson(sessionJson);

            // Vérifier le contexte de sortie via un snapshot Verify.
            // Lors du premier lancement, le fichier .verified.txt est créé.
            // Les exécutions suivantes vérifient que la sortie n'a pas changé.
            await Verifier.Verify(outputContext)
                .UseDirectory("TestData")
                .UseFileName("MyPlugin_Create_contact");
        }

    }
}
