//HintName: MyPlugin_Create_contact_SessionTests.g.cs
// <auto-generated/>
// Generated by XrmFramework.RemoteDebugger.Generator
// Do not modify this file manually.
// To regenerate, simply rebuild after modifying the .pluginsession.json files.

using System.Threading.Tasks;
using VerifyXunit;
using Xunit;
using XrmFramework.RemoteDebugger.Common;

namespace XrmFramework.RemoteDebugger.Generated
{
    /// <summary>
    /// Automatically generated unit tests for <c>MyPlugin_Create_contact</c>.
    /// Each method replays a recorded remote debugging session
    /// and verifies that the output context matches the Verify snapshot.
    /// </summary>
    [UsesVerify]
    public class MyPlugin_Create_contact_SessionTests
    {
        /// <summary>
        /// Replays the recorded session from file: MyPlugin_Create_contact.pluginsession.json
        /// </summary>
        [Fact]
        public async Task Session_MyPlugin_Create_contact()
        {
            // JSON of the session recorded during remote debugging
            // (embedded directly to avoid any dependency on external files)
            const string sessionJson = @"{
  ""pluginTypeName"": ""MyPlugin"",
  ""message"": ""Create"",
  ""stage"": 20,
  ""entityName"": ""contact"",
  ""capturedAt"": ""2025-01-01T00:00:00Z"",
  ""inputParameters"": {},
  ""preImages"": {},
  ""postImages"": {}
}";

            // Run the plugin with the recorded input context,
            // replaying all CRM calls from the recorded responses.
            var outputContext = PluginTestRunner.RunFromJson(sessionJson);

            // Verify the output context via a Verify snapshot.
            // On first run, the .verified.txt file is created.
            // Subsequent runs verify that the output hasn't changed.
            await Verifier.Verify(outputContext)
                .UseDirectory("TestData")
                .UseFileName("MyPlugin_Create_contact");
        }

    }
}
