// Copyright (c) Christophe Gondouin (CGO Conseils). All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.CodeDom.Compiler;

namespace XrmFramework.DeployUtils.Tests.TableSync.Fixtures
{
    // ──────────────────────────────────────────────────────────────────────────
    // The DefinitionAnalyzer matches attributes by SIMPLE NAME. The test project
    // already references the real [EntityDefinition] (via the linked sources
    // from XrmFramework.Tests), so it is used directly.
    //
    // All fixtures are prefixed with "TableSyncTest" to avoid collisions with
    // the Definition fixtures already present in the shared test sources
    // (Contact, Account, Dummy, Foo, etc.).
    // ──────────────────────────────────────────────────────────────────────────

    // ──────────────────────────────────────────────────────────────────────────
    // "Classic" fixture: C# Definition hand-written by the user.
    // Expected TableName: "TableSyncTestContact".
    // ──────────────────────────────────────────────────────────────────────────

    [EntityDefinition]
    public static class TableSyncTestContactDefinition
    {
        public const string EntityName = "tabsync_contact";
        public const string EntityCollectionName = "tabsync_contacts";

        public static class Columns
        {
            public const string Id = "tabsync_contactid";
            public const string FirstName = "tabsync_firstname";
            public const string LastName = "tabsync_lastname";
            public const string Email = "tabsync_email";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Entirely generated by the Roslyn TableSourceFileGenerator.
    // Expected TableName: "TableSyncTestAccount".
    // ──────────────────────────────────────────────────────────────────────────

    [GeneratedCode("XrmFramework", "2.0")]
    [EntityDefinition]
    public static class TableSyncTestAccountDefinition
    {
        public const string EntityName = "tabsync_account";
        public const string EntityCollectionName = "tabsync_accounts";

        public static class Columns
        {
            public const string Id = "tabsync_accountid";
            public const string Name = "tabsync_name";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // No "Definition" suffix -> the class name is kept as-is
    // as TableName ("TableSyncTestNoSuffix").
    // ──────────────────────────────────────────────────────────────────────────

    [EntityDefinition]
    public static class TableSyncTestNoSuffix
    {
        public const string EntityName = "tabsync_nosuffix";
        public const string EntityCollectionName = "tabsync_nosuffixes";

        public static class Columns
        {
            public const string Id = "tabsync_nosuffixid";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // No EntityName field -> MUST be ignored by the analyzer.
    // ──────────────────────────────────────────────────────────────────────────

    [EntityDefinition]
    public static class TableSyncTestIncompleteDefinition
    {
        public static class Columns
        {
            public const string Id = "tabsync_incompleteid";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // No [EntityDefinition] -> MUST be ignored by the analyzer.
    // ──────────────────────────────────────────────────────────────────────────

    public static class TableSyncTestNotADefinition
    {
        public const string EntityName = "tabsync_ghost";

        public static class Columns
        {
            public const string Id = "tabsync_ghostid";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // With EntityName but an empty Columns -> 0 columns, a legitimate case.
    // ──────────────────────────────────────────────────────────────────────────

    [EntityDefinition]
    public static class TableSyncTestEmptyDefinition
    {
        public const string EntityName = "tabsync_empty";
        public const string EntityCollectionName = "tabsync_empties";

        public static class Columns
        {
            // intentionally empty
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // No EntityCollectionName -> CollectionName must be null.
    // ──────────────────────────────────────────────────────────────────────────

    [EntityDefinition]
    public static class TableSyncTestNoCollectionDefinition
    {
        public const string EntityName = "tabsync_nocoll";

        public static class Columns
        {
            public const string Id = "tabsync_nocollid";
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Columns carrying [OptionSet(typeof(...))]: the enum's C# name is a project
    // decision the CRM knows nothing about, and must be recovered from the assembly.
    // ──────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Members renamed by hand: the generator would have derived "Actif"/"Modele" from the CRM
    /// labels, and the project's code compiles against these names instead.
    /// </summary>
    public enum TableSyncTestRenamedStatus
    {
        EnCours = 1,
        Termine = 2,
        Modele = 3
    }

    /// <summary>
    /// Allows an empty value: the generator prepends a synthetic "Null = 0" that mirrors
    /// HasNullValue rather than any CRM option.
    /// </summary>
    public enum TableSyncTestRenamedGlobal
    {
        Null = 0,
        Oui = 1,
        Non = 2
    }

    [EntityDefinition]
    public static class TableSyncTestOptionSetDefinition
    {
        public const string EntityName = "tabsync_optionset";
        public const string EntityCollectionName = "tabsync_optionsets";

        public static class Columns
        {
            public const string Id = "tabsync_optionsetid";

            [AttributeMetadata(AttributeTypeCode.Picklist)]
            [OptionSet(typeof(TableSyncTestRenamedStatus))]
            public const string StatusCode = "statuscode";

            [AttributeMetadata(AttributeTypeCode.Picklist)]
            [OptionSet(typeof(TableSyncTestRenamedGlobal))]
            public const string GlobalPick = "tabsync_globalpick";

            /// <summary>No option set: OptionSetName must stay null.</summary>
            [AttributeMetadata(AttributeTypeCode.String)]
            public const string Name = "tabsync_name";
        }
    }
}
